### PR TITLE
add MobilEye to users

### PR DESCRIPTION
**Pull request by flaviuvadan**
@bchalk101 and @harelwa I am wondering if you and MobilEye are open to listing the organization as users of Hera via `USERS.md`? 🙂 I think it would strengthen Hera's presence in the community and help with adoption!

### CODE REVIEW

**Comment by bchalk101** [comment]
Hey @flaviuvadan - will have to check that this is ok from our side and get back to you

**Comment by flaviuvadan** [comment]
any update @bchalk101? 🙂

**Comment by flaviuvadan** [comment]
Circling back to this - any updates @bchalk101? 🙂 Would love to see MobilEye on the list of users

**Comment by flaviuvadan** [comment]
Hey @bchalk101 will close this for now but feel free to suggest the addition if you'd like! 🙂

**Pull request closed without merging**
