### PR TITLE
Support cluster_scope in TemplateRef

### PR DESCRIPTION
**Pull request by szdr**
`IoArgoprojWorkflowV1alpha1TemplateRef` allows setting cluster_scope.

https://github.com/argoproj/argo-workflows/blob/master/sdks/python/client/docs/IoArgoprojWorkflowV1alpha1TemplateRef.md

TemplateRef can now set cluster_scope as well.

(I left the default value of cluster_scope as False so as not to affect existing scripts. What do you think?)

### CODE REVIEW

**Comment by flaviuvadan** [comment]
Thank you for the PR @szdr! Yes, Hera should support this scope 🙂  any chance you can upgrade the version (3.2.0) and add a CHANGELOG entry for this addition?

**Comment by flaviuvadan** [comment]
Thank you for the PR @szdr! Yes, Hera should support this scope 🙂  any chance you can upgrade the version (3.2.0) and add a CHANGELOG entry for this addition?

**Comment by flaviuvadan** [comment]
@szdr thank you for the contribution! 🙂 I see you have other PRs as well. What do you think about merging the other PRs into this one and we release 3.2.0 with 3-4 features?

**Comment by szdr** [comment]
@flaviuvadan Thanks for the review.

> What do you think about merging the other PRs into this one and we release 3.2.0 with 3-4 features?

OK. I will direct the merge destination of other PRs to this branch.

**Comment by szdr** [comment]
@flaviuvadan 
Oops, this branch is on my fork.
Could you please create a branch (`argoproj-labs:3.2.0`) for version updates?
I will direct the PRs I am sending out to that branch.

**Review by flaviuvadan — APPROVED** [review]
Thank you @szdr! 🚀  Merging this into `argoproj-lab:hera/3.2.0`!

**Pull request merged**
