### PR TITLE
Fix input_from behavior without func

### LINKED ISSUE #167: Cannot use input_from without func
I want use input_from without func. But, the following code doesn't work...

```python
Task(
    "test",
    command=['python'],
    args=['-c', 'print("{{inputs.parameters.value}}"'],
    input_from=InputFrom(name='generate', parameters=['value'])
)
```

Above code gets following error.

```
  File "/lib/python3.9/site-packages/hera/task.py", line 294, in __init__
    self.parameters = self.get_parameters()
  File "/lib/python3.9/site-packages/hera/task.py", line 701, in get_parameters
    args = set(inspect.getfullargspec(self.func).args).intersection(set(self.input_from.parameters))
  File "/lib/python3.9/inspect.py", line 1171, in getfullargspec
    raise TypeError('unsupported callable') from ex
TypeError: unsupported callable
```

### PR DESCRIPTION
**Pull request by kitagry**
fix #167

### CODE REVIEW

**Comment by flaviuvadan** [comment]
Thank you for the issue report and quick fix @kitagry! 🙂 Gentle reminder to bump the version and document the fix in a changelog. 3.3.1, perhaps?

**Comment by flaviuvadan** [comment]
@kitagry any chance you had the opportunity to test the example in the issue? Seems interesting to me to have a `python -c "print("{{input....}}")" work, actually, and I want to make sure we know it works as expected. I would be surprised as I expect Argo to only do replacements for variables in its own objects but not in used provided container scripts 🤔

**Comment by flaviuvadan** [comment]
@kitagry I tested this myself really quick and it works just fine 🚀 I was wrong about the `{{...}}` as Argo replaced the `input.parameters` in the `-c` Python call as well. This is the script I ran successfully: 
```python
from hera import Task, Workflow, InputFrom, WorkflowService


def gen():
    import sys
    import json
    json.dump([{'value': i} for i in range(1)], sys.stdout)


ws = WorkflowService(...)
w = Workflow('fv-test', ws)
gen = Task('gen', gen)
con = Task(
    'con',
    command=['python'],
    args=['-c', 'print("{{inputs.parameters.value}}")'],
    input_from=InputFrom(name=gen.name, parameters=['value'])
)
gen >> con
w.add_tasks(gen, con)
w.create()
```

**Review by flaviuvadan — APPROVED** [review]

**Comment by kitagry** [comment]
Oh, I'm sorry for late reply! Thank you for the test!!

**Pull request merged**
