### PR TITLE
Migrate completely to makefile and cleanup github actions 

### PR DESCRIPTION
**Pull request by samj1912**
- Cleans up the makefile and CI targets.
- Moves linting to `ruff` to get auto-formatting for flake8/isort.
- Consolidate codecov in CI. Codecov is smart enough to collate coverage reports from a matrix together.
- Make output model files reproducible. Remove timestamp.
- Update to latest action versions to ensure we are not on node 12
- Update CI to use min python 3.8 since 3.7 is unsupported

### CODE REVIEW

**Review by flaviuvadan — COMMENTED** [review]
Maybe the `toxenv: 'py311'` specification from the matrix build can be removed as well?

**Review by flaviuvadan — APPROVED** [review]

**Comment by samj1912** [comment]
@flaviuvadan done. Also updated the readme and contribution guidelines.

**Comment by flaviuvadan** [comment]
> @flaviuvadan done. Also updated the readme and contribution guidelines.

Will push as soon as CI passes!

**Comment by samj1912** [comment]
All good to go 🚀

**Comment by samj1912** [comment]
Superceded by https://github.com/argoproj-labs/hera-workflows/pull/451

**Pull request merged**
