### PR TITLE
Add a script and tox target to auto-generate example markdowns

### LINKED ISSUE #349: Suggestion: Improve example documentation generation
Currently I see that the examples directory has to be manually synced between the python examples and the markdown ones. Could we somehow have tooling that auto-generates the markdown examples from python ones? This would help keep the two directories in sync and potentially improve the contribution experience.

### PR DESCRIPTION
**Pull request by samj1912**
Signed-off-by: Sambhav Kothari <skothari44@bloomberg.net>

Fixes #349

This ensures that the doc's examples folder is in sync with the examples scripts folder.

@flaviuvadan also automatically generated some missing example files and updated some existing ones which had drifted.

### CODE REVIEW

**Comment by samj1912** [comment]
Output documentation - https://hera-workflows--390.org.readthedocs.build/en/390/

**Review by flaviuvadan — APPROVED** [review]
This looks like an awesome first version of auto-gen examples!!

**Comment by flaviuvadan** [comment]
Any chance you are open to updating the [contribution guideline](https://github.com/argoproj-labs/hera-workflows/blob/main/CONTRIBUTING.md)? :)

**Comment by samj1912** [comment]
@flaviuvadan added :)

**Review by flaviuvadan — APPROVED** [review]

**Comment by flaviuvadan** [comment]
Awesome work @samj1912 this is very cool

**Pull request merged**
