### PR TITLE
feat: Add verify flag to workflow/cron workflow service

### LINKED ISSUE #16: How to ignore certificate errors?
When I attempt to port-forward Argo running in GKE, I get a certificate error. I tried the [suggestion from the first comment here](https://stackoverflow.com/a/36601223), but I still get the certificate error.

```
C:\Users\ryanr\Code\hera-workflows\examples [main ≡ +0 ~1 -0 !]> python .\diamond.py
Traceback (most recent call last):
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\urllib3\connectionpool.py", line 706, in urlopen      
    chunked=chunked,
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\urllib3\connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\urllib3\connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\urllib3\connection.py", line 426, in connect
    tls_in_tls=tls_in_tls,
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\urllib3\util\ssl_.py", line 450, in ssl_wrap_socket
    sock, context, tls_in_tls, server_hostname=server_hostname
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\urllib3\util\ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2544.0_x64__qbz5n2kfra8p0\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".\diamond.py", line 32, in <module>
    w.submit()
  File "c:\users\ryanr\code\hera-workflows\src\hera\v1\workflow.py", line 129, in submit
    self.service.submit(self.workflow, namespace)
  File "c:\users\ryanr\code\hera-workflows\src\hera\v1\workflow_service.py", line 48, in submit
    return self.service.create_workflow(namespace, V1alpha1WorkflowCreateRequest(workflow=workflow))
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\argo\workflows\client\api\workflow_service_api.py", line 62, in create_workflow
    return self.create_workflow_with_http_info(namespace, body, **kwargs)  # noqa: E501
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\argo\workflows\client\api\workflow_service_api.py", line 162, in create_workflow_with_http_info
    collection_formats=collection_formats)
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\argo\workflows\client\api_client.py", line 369, in call_api
    _preload_content, _request_timeout, _host)
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\argo\workflows\client\api_client.py", line 185, in __call_api
    _request_timeout=_request_timeout)
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\argo\workflows\client\api_client.py", line 413, in request
    body=body)
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\argo\workflows\client\rest.py", line 271, in POST
    body=body)
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\argo\workflows\client\rest.py", line 168, in request
    headers=headers)
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\urllib3\request.py", line 79, in request
    method, url, fields=fields, headers=headers, **urlopen_kw
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\urllib3\connectionpool.py", line 796, in urlopen
    **response_kw
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\urllib3\connectionpool.py", line 796, in urlopen
    **response_kw
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\urllib3\connectionpool.py", line 796, in urlopen
    **response_kw
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\urllib3\connectionpool.py", line 756, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "C:\Users\ryanr\.virtualenvs\hera-workflows-FA8T1hb6\lib\site-packages\urllib3\util\retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=2746): Max retries exceeded with url: /api/v1/workflows/default (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1091)')))
```

### PR DESCRIPTION
**Pull request by flaviuvadan**
There are use cases in which users have deployments with self-signed certificates. When port forwarding to an Argo deployment with such a certificate, Hera should instantiate the Argo config to skip certificate validation. By default, validation will be performed, but the `verify` flag allows users to control this behavior. 

This fixes #16.

### CODE REVIEW

**Comment by flaviuvadan** [comment]
@tachyus-ryan and @bartcode, let me know what you think about this! Not sure whether you have the time but it would be amazing if you could test this with your setup. That way we perform some brief testing in different environments.

**Comment by bartcode** [comment]
Thanks so much for getting to this so quickly! Unfortunately, it doesn't work for me yet. When I use the default, I got this:

```
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='my-hostname.com', port=443): Max retries exceeded with url: /api/v1/workflows/default (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1129)')))
```

Now, with `verify=False`, I'm seeing this:

```
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='my-hostname', port=80): Max retries exceeded with url: /api/v1/workflows/default (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x106d195b0>: Failed to establish a new connection: [Errno 60] Operation timed out'))
```

I believe this should still be port 443 then. But there's actually one more rather important detail to my current use case: Argo Workflows is running on `my-hostname.com/argo-workflows`. There's probably a good reason for this, but why not specify the full URL instead of the domain as an input to `WorkflowService`?

```
ws = WorkflowService("https://my-domain.com/workflows", verify=False)
```

I can imagine this might be harder to change now, so perhaps something like this would also be an option:
```
ws = WorkflowService("my-domain.com", port=443, path="/workflows" verify=False)
```

**Comment by flaviuvadan** [comment]
@bartcode after some further evaluation, I think the solution you proposed is likely the best. The one where we use the service like so, but use `verify=False`:
```python
ws = WorkflowService("https://argo.my-hostname.com", verify=False)
```

This is actually how the examples of the autogenerated Argo Workflows Python SDK use it. This is breaking change, however, so I am wondering if we can strike a balance... what do you think about adding kwargs to `WorkflowService` that have the scheme, domain, port, and whether to verify TLS? Like so:
```python
WorkflowService(domain: str, token: str, namespace: str = 'default', scheme: Optional[str] = 'https', port: Optional[int] = None, verify_ssl: bool = True)

Config(domain: str, scheme: Optional[str] = 'https', port: Optional[int] = None, verify_ssl: bool = True)
```

Then, the `Config._get_config(...)` can assemble, in your case:
```
...
config.verify_ssl = False
addr = f'{scheme}://{host}:{port}' if port else f'{scheme}://{host}'  # https://my-hostname.com/argo-workflows but with verify_ssl = False now

```

**Comment by bartcode** [comment]
Really? I deleted part of my comment, because I wasn't entirely sure whether you were using the Kubernetes API or the Argo Workflows API. 😅 

I think your proposal is good. I must say, though, that I've by now installed a valid certificate on my service, so I won't have the issue anymore. But I still think it's good to have it fixed.

**Comment by flaviuvadan** [comment]
> Really? I deleted part of my comment, because I wasn't entirely sure whether you were using the Kubernetes API or the Argo Workflows API. 😅
> 
> I think your proposal is good. I must say, though, that I've by now installed a valid certificate on my service, so I won't have the issue anymore. But I still think it's good to have it fixed.

Awesome! So happy to hear that you're able to use Hera now 🙂  Hopefully that did not cause too much hassle... Anyway, yes, we should be a bit more in line with usages of the Argo Python SDK in this case, so we can definitely make the change.

**Comment by flaviuvadan** [comment]
@bartcode I think initializing the configuration and the API the same way the new SDK does in Argo Workflows is the way to go: https://github.com/argoproj/argo-workflows/pull/7363/files#diff-855bbba911df7cc070468cdafda8c55838dad67147473b25bb38d707d986c3b3L32 We can likely create a V2 configuration, which can be completely backwards compatible with V1, to support users in (1) adopting Hera, particularly if they have a setup similar the one you work with, and (2) be a bit more consistent with core Python SDK usage.

**Comment by dixon1e** [comment]
Hello @flaviuvadan is there any help needed to move this forward? The use case that we are experiencing is simply providing clusters for science workflow authors on their laptops. This change will help nicely, we don't want to manage certs to do this.

**Comment by flaviuvadan** [comment]
> The use case that we are experiencing is simply providing clusters for science workflow authors on their laptops
First, thank you for sharing this, that's awesome 🙂 

> we don't want to manage certs to do this
Very reasonable. I plan to tackle #7 this upcoming weekend and after that I will change the configuration such that it provides control over the scheme that is used, and whether to `verify_ssl`. I am leaving this open for the discussion and will tag you and bartcode in the new PRs.

**Comment by flaviuvadan** [comment]
I am going to close this for now. Please see #40 and #41. I am going to tackle those soon.

**Pull request closed without merging**
