### PR TITLE
Automate the release/changelog process

### LINKED ISSUE #334: Suggestion: Set up release automation and changelog
It would be great if the hera release process could be automated.

Some examples of how it can be done are - 

- https://github.com/cruft/cruft/blob/master/.github/workflows/pypi_publish.yml and https://github.com/cruft/cruft/blob/master/.github/workflows/test_pypi_publish.yml

The above releases the package on PyPI automatically through the Github UI by creating a release.

You can also couple it with release drafter which will give you nice changelogs like https://github.com/buildpacks/libcnb/releases

### LINKED ISSUE #379: Add git tags and releases
Hi,

It would be great if `version git tags` along with corresponding `releases` were added for published versions.

Similar to:

https://github.com/argoproj/argo-workflows/tags
https://github.com/argoproj/argo-workflows/releases

If usage motivation is not clear, pls let me know and i'll elaborate.

Thanks,
Harel

### PR DESCRIPTION
**Pull request by samj1912**
Fixes #379 
Fixes #334 

This PR adds an automated version bumping/changlog generation process and an easy to use release process that can be released via the UI. See RELEASE.md for more details.

Rendered [RELEASE.md](https://github.com/samj1912/hera-workflows/blob/github-workflow/RELEASE.md)

### CODE REVIEW

**Comment by samj1912** [comment]
The labels should automatically synchronize in the repository once this PR is merged. Meanwhile, @flaviuvadan you will need to set `type:task` and `semver:patch` labels on this PR.

**Comment by samj1912** [comment]
This can eventually be coupled with https://github.com/ewjoachim/sphinx-github-changelog for publishing to the docs page.

**Review by flaviuvadan — APPROVED** [review]
Awesome contribution @samj1912 :) Will test with a patch release soon! 

One clarification:
- if non-code changes are release those will receive a default PATCH assignment, correct?

**Comment by samj1912** [comment]
> if non-code changes are release those will receive a default PATCH assignment, correct?

every PR needs a semver label. The semver labels decide the version bump.

We can use the auto-labeler if we want to automate it, but currently it requires a maintainer to label every PR with the version and type label.

auto labeler - https://github.com/marketplace/actions/release-drafter#autolabeler

**Pull request merged**
